<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Audex.Infrastructure.Tests</RootNamespace>
    <AssemblyName>Audex.Infrastructure.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="NSubstitute" Version="6.1.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Shared\Shared.csproj" />
    <ProjectReference Include="..\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Audex.Tests.Shared" />
    <Using Include="Audex.Tests.Shared.Fixtures" />
  </ItemGroup>

</Project>
