services:
  db_mongo:
    image: mongo
    container_name: money_manager_db
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - mongo-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - data-volume:/data/db
  mongo-express:
    image: mongo-express
    container_name: money_manager_db_ui
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${EXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_LOGIN}:${MONGO_PASSWORD}@db_mongo:27017/?authSource=admin
    restart: always
    networks:
      - mongo-network
    ports:
      - 8081:8081
    depends_on:
      - db_mongo
  server:
    build: ./server
    container_name: money_manager_server
    networks:
      - server-network
      - mongo-network
    ports:
      - ${SERVER_PORT}:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_ENVIRONMENT=Release
      - MongoDB__ConnectionString=mongodb://${MONGO_LOGIN}:${MONGO_PASSWORD}@db_mongo:27017/?authSource=admin
      - MongoDB__DatabaseName=${MONGO_DB}
      - Client__Url=${CLIENT_HOST}:${CLIENT_PORT}
    depends_on:
      - db_mongo
    restart: always
  client:
    container_name: money_manager_client
    networks:
      - server-network
    build: 
      context: ./client
      args:
        SERVER_API_URL: "${SERVER_HOST}:${SERVER_PORT}"
    ports:
      - ${CLIENT_PORT}:80

networks:
  mongo-network:
  server-network:

volumes:
  data-volume: