version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - data-volume:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  server:
      build: ./server
      restart: always
      ports:
        - ${SERVER_PORT}:80
      environment:
        MongoDB__Host: mongo
        Client__Url: ${CLIENT_HOST}:${CLIENT_PORT}
      depends_on:
        - mongo
 
  client:
    build: 
      context: ./client
      args:
        SERVER_URL: ${SERVER_HOST}:${SERVER_PORT}
    ports:
      - ${CLIENT_PORT}:80
    stdin_open: true
    tty: true

volumes:
  data-volume: