// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyManager.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103121155_AddBankIcon")]
    partial class AddBankIcon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Accounts.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a08f5553-379e-4294-a2e5-75e88219433c"),
                            Active = true,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = new Guid("cda2ce07-551e-48cf-988d-270c0d022866"),
                            Active = true,
                            Name = "Debit card"
                        },
                        new
                        {
                            Id = new Guid("6ea1867f-c067-412c-b443-8b9bc2467202"),
                            Active = true,
                            Name = "Credit card"
                        });
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Banks.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Broker");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MainCurrencyAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TypeId");

                    b.ToTable("BrokerAccount");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccountFundsTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Income")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BrokerAccountId");

                    b.ToTable("BrokerAccountFundsTransfer");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccountSecurity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrokerAccountId");

                    b.HasIndex("SecurityId");

                    b.ToTable("BrokerAccountSecurity");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BrokerAccountType");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.DividendPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DividendId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ReceivedAt")
                        .HasColumnType("date");

                    b.Property<int>("SecuritiesQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BrokerAccountId");

                    b.HasIndex("DividendId");

                    b.ToTable("DividendPayment");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.CryptoAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CryptoProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CryptoProviderId");

                    b.ToTable("CryptoAccount");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.CryptoAccountCryptocurrency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrpytocurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CryptoAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CrpytocurrencyId");

                    b.HasIndex("CryptoAccountId");

                    b.ToTable("CryptoAccountCryptocurrency");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.CryptoProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CryptoProvider");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.Cryptocurrency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cryptocurrency");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Currencies.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7f31af3-5091-439c-8854-c90872420ecf"),
                            Active = true,
                            Name = "USD",
                            Rate = 0m
                        },
                        new
                        {
                            Id = new Guid("08762100-b4e0-4a70-b48c-dd9e9411c4a2"),
                            Active = true,
                            Name = "RUB",
                            Rate = 0m
                        },
                        new
                        {
                            Id = new Guid("4c073dc4-20be-44d4-80c9-3f09d4ac12ef"),
                            Active = true,
                            Name = "EUR",
                            Rate = 0m
                        });
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Debts.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Debt");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Debts.DebtPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DebtId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.HasIndex("TargetAccountId");

                    b.ToTable("DebtPayment");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Deposits.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedEarn")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Deposit");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.Dividend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("DeclarationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId");

                    b.ToTable("Dividend");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("IconKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PriceFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ticker")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TypeId");

                    b.ToTable("Security");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.SecurityTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BrokerCommission")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StockExchangeCommission")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BrokerAccountId");

                    b.HasIndex("SecurityId");

                    b.ToTable("SecurityTransaction");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.SecurityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SecurityType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23b0a73a-9ac1-4fb5-a763-3c10424ed798"),
                            Name = "Stock"
                        },
                        new
                        {
                            Id = new Guid("16184209-1716-4854-a293-75776e1b4ec0"),
                            Name = "Bond"
                        },
                        new
                        {
                            Id = new Guid("209dcb50-989f-44f7-b886-0d7f5c763593"),
                            Name = "Investment fund unit"
                        },
                        new
                        {
                            Id = new Guid("2ccd0a40-4339-4be7-9f4d-fbf5c31b20c2"),
                            Name = "Currency"
                        });
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Transactions.CurrencyTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("SourceAccountId");

                    b.ToTable("CurrencyTransaction");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cashback")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Transactions.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("IconKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransactionType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe21a187-2963-43d0-b27e-84f372504028"),
                            Active = false,
                            Name = "System"
                        });
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.User.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e2104a4-4b8d-4d4c-8585-0b24cf11e891"),
                            CurrencyId = new Guid("c7f31af3-5091-439c-8854-c90872420ecf"),
                            LanguageCode = "EN"
                        });
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Accounts.Account", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Accounts.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Banks.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyManager.Infrastructure.Entities.Currencies.Currency", "Currency")
                        .WithMany("Accounts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Bank");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccount", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Banks.Bank", "Bank")
                        .WithMany("BrokerAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyManager.Infrastructure.Entities.Brokers.Broker", "Broker")
                        .WithMany("BrokerAccounts")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Currencies.Currency", "Currency")
                        .WithMany("BrokerAccounts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccountType", "Type")
                        .WithMany("BrokerAccounts")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Broker");

                    b.Navigation("Currency");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccountFundsTransfer", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Accounts.Account", "Account")
                        .WithMany("BrokerAccountFundsTransfers")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccount", "BrokerAccount")
                        .WithMany("BrokerAccountFundsTransfers")
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("BrokerAccount");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccountSecurity", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccount", "BrokerAccount")
                        .WithMany("BrokerAccountSecurities")
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Securities.Security", "Security")
                        .WithMany("BrokerAccountSecurities")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrokerAccount");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.DividendPayment", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccount", "BrokerAccount")
                        .WithMany("DividendPayments")
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Securities.Dividend", "Dividend")
                        .WithMany("DividendPayments")
                        .HasForeignKey("DividendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrokerAccount");

                    b.Navigation("Dividend");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.CryptoAccount", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Crypto.CryptoProvider", "CryptoProvider")
                        .WithMany("CryptoAccounts")
                        .HasForeignKey("CryptoProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CryptoProvider");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.CryptoAccountCryptocurrency", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Crypto.Cryptocurrency", "Cryptocurrency")
                        .WithMany("CryptoAccountCryptocurrencies")
                        .HasForeignKey("CrpytocurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Crypto.CryptoAccount", "CryptoAccount")
                        .WithMany("CryptoAccountCryptocurrencies")
                        .HasForeignKey("CryptoAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CryptoAccount");

                    b.Navigation("Cryptocurrency");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Debts.Debt", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Currencies.Currency", "Currency")
                        .WithMany("Debts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Debts.DebtPayment", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Debts.Debt", "Debt")
                        .WithMany("DebtPayments")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Accounts.Account", "TargetAccount")
                        .WithMany("DebtPayments")
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Debt");

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Deposits.Deposit", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Banks.Bank", "Bank")
                        .WithMany("Deposits")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyManager.Infrastructure.Entities.Currencies.Currency", "Currency")
                        .WithMany("Deposits")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.Dividend", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Securities.Security", "Security")
                        .WithMany("Dividends")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Security");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.Security", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Currencies.Currency", "Currency")
                        .WithMany("Securities")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Securities.SecurityType", "Type")
                        .WithMany("Securities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.SecurityTransaction", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccount", "BrokerAccount")
                        .WithMany("SecurityTransactions")
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Securities.Security", "Security")
                        .WithMany("SecurityTransactions")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrokerAccount");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Transactions.CurrencyTransaction", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Accounts.Account", "DestinationAccount")
                        .WithMany("DestinationCurrencyTransactions")
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Accounts.Account", "SourceAccount")
                        .WithMany("SourceCurrencyTransactions")
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationAccount");

                    b.Navigation("SourceAccount");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Transactions.Transaction", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Accounts.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyManager.Infrastructure.Entities.Transactions.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.User.UserProfile", b =>
                {
                    b.HasOne("MoneyManager.Infrastructure.Entities.Currencies.Currency", "Currency")
                        .WithMany("UserProfiles")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Accounts.Account", b =>
                {
                    b.Navigation("BrokerAccountFundsTransfers");

                    b.Navigation("DebtPayments");

                    b.Navigation("DestinationCurrencyTransactions");

                    b.Navigation("SourceCurrencyTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Accounts.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Banks.Bank", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BrokerAccounts");

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.Broker", b =>
                {
                    b.Navigation("BrokerAccounts");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccount", b =>
                {
                    b.Navigation("BrokerAccountFundsTransfers");

                    b.Navigation("BrokerAccountSecurities");

                    b.Navigation("DividendPayments");

                    b.Navigation("SecurityTransactions");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Brokers.BrokerAccountType", b =>
                {
                    b.Navigation("BrokerAccounts");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.CryptoAccount", b =>
                {
                    b.Navigation("CryptoAccountCryptocurrencies");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.CryptoProvider", b =>
                {
                    b.Navigation("CryptoAccounts");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Crypto.Cryptocurrency", b =>
                {
                    b.Navigation("CryptoAccountCryptocurrencies");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Currencies.Currency", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BrokerAccounts");

                    b.Navigation("Debts");

                    b.Navigation("Deposits");

                    b.Navigation("Securities");

                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Debts.Debt", b =>
                {
                    b.Navigation("DebtPayments");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.Dividend", b =>
                {
                    b.Navigation("DividendPayments");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.Security", b =>
                {
                    b.Navigation("BrokerAccountSecurities");

                    b.Navigation("Dividends");

                    b.Navigation("SecurityTransactions");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Securities.SecurityType", b =>
                {
                    b.Navigation("Securities");
                });

            modelBuilder.Entity("MoneyManager.Infrastructure.Entities.Transactions.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
